apiVersion: apps/v1
kind: Deployment

metadata:
  name: database-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: db-container
        image: krzysztofkalita/kubernetes_demo_app:db_image
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root_password"
          - name: MYSQL_DATABASE
            value: "PostDB"
          - name: MYSQL_USER
            value: "db_user"
          - name: MYSQL_PASSWORD
            value: "db_password"
        ports:
        - containerPort: 3306
