apiVersion: apps/v1
kind: Deployment

metadata:
  name: crudapp-deployment
  labels:
    app: crudapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudapp

  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
      - name: crudapp-container
        image: krzysztofkalita/kubernetes_demo_app:crudapp_image
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: MYSQL_USER
                name: db-secret
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: db-secret
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                key: MYSQL_HOST
                name: db-configmap
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                key: MYSQL_PORT
                name: db-configmap
          - name: MYSQL_DB
            valueFrom:
              configMapKeyRef:
                key: MYSQL_DB
                name: db-configmap
