apiVersion: v1
kind: Service

metadata:
  name: crudapp-service

spec:
  selector:
    app: crudapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
