apiVersion: apps/v1
kind: Deployment

metadata:
  name: crudapp-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
      - name: crudapp-container
        image: mateusz1982/kubernetes_demo:crudapp_image
        envFrom:
          - configMapRef:
              name: db-configmap
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
